# ~/.ssh: config from the template, Bitwarden's SSH agent, key permissions.

register ssh "SSH                   (config, Bitwarden agent, server list, key perms)"

# Bitwarden exposes a different socket per install flavour: App Store builds are
# sandboxed into ~/Library/Containers, the .dmg build is not, and snap/flatpak
# each get their own root. So the path is detected per machine instead of being
# committed, and written to a machine-local include.
BW_SOCKETS="
$HOME/.bitwarden-ssh-agent.sock
$HOME/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock
$HOME/snap/bitwarden/current/.bitwarden-ssh-agent.sock
$HOME/.var/app/com.bitwarden.desktop/data/.bitwarden-ssh-agent.sock
"

step_ssh() {
  task "~/.ssh"              _ssh_dirs
  task "~/.ssh/config"       _ssh_config
  task "Bitwarden SSH agent" _ssh_agent
  # Reads stdin, so it cannot live inside task(): the spinner owns the line and
  # would redraw over whatever is being typed. Prompt first, write in a task.
  _ssh_hosts_prompt
  task "Server list"         _ssh_hosts_write
  task "Key permissions"     _ssh_perms
}

_ssh_dirs() {
  mkdir -p "$HOME/.ssh/config.d"
  chmod 700 "$HOME/.ssh" "$HOME/.ssh/config.d"
}

# Copied, not symlinked: this file names real servers and the repo is public.
_ssh_config() {
  if [ ! -f "$HOME/.ssh/config" ]; then
    cp "$DOTFILES/home/.ssh/config.example" "$HOME/.ssh/config"
    chmod 600 "$HOME/.ssh/config"
    task_note "created, put real hosts in ~/.ssh/config.d/*.conf"
    return 0
  fi

  # An existing config is never overwritten, but it is useless without the
  # include, so add just that line. Prepending is safe and required: ssh is
  # first-match-wins, so an include below an existing Host * would be ignored.
  if grep -q 'config\.d' "$HOME/.ssh/config"; then
    task_skip "already present, include in place"
    return 0
  fi
  {
    echo "# Added by dotfiles: agent socket and private host list."
    echo "Include ~/.ssh/config.d/*.conf"
    echo
    cat "$HOME/.ssh/config"
  } > "$HOME/.ssh/config.new"
  mv "$HOME/.ssh/config.new" "$HOME/.ssh/config"
  chmod 600 "$HOME/.ssh/config"
  task_note "kept yours, added the config.d include on top"
}

_ssh_agent() {
  local sock="" candidate
  while read -r candidate; do
    [ -z "$candidate" ] && continue
    [ -S "$candidate" ] && { sock="$candidate"; break; }
  done <<INNER
$BW_SOCKETS
INNER

  # No socket means the agent is off or Bitwarden is closed. Write the path it
  # will use anyway, so enabling it later needs no second install run.
  local running=1
  if [ -z "$sock" ]; then
    running=0
    if is_macos && [ -d "$HOME/Library/Containers/com.bitwarden.desktop" ]; then
      sock="$HOME/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock"
    else
      sock="$HOME/.bitwarden-ssh-agent.sock"
    fi
  fi

  cat > "$HOME/.ssh/config.d/00-agent.conf" <<INNER
# Generated by ./install.sh ssh. Machine-specific, do not commit.
# Regenerate after switching Bitwarden install flavour: ./install.sh ssh
Host *
	IdentityAgent $sock
INNER
  chmod 600 "$HOME/.ssh/config.d/00-agent.conf"

  if [ "$running" = 1 ]; then
    task_note "socket live"
  else
    task_note "enable it: Bitwarden > Settings > Allow SSH agent"
  fi
}

SSH_HOSTS_FILE="$HOME/.ssh/config.d/10-servers.conf"

# Whatever pipes a file to the clipboard here. Printed in hints, never run for
# the user: copying their server list to the clipboard is their call.
_ssh_clip_cmd() {
  if has pbcopy; then       echo "pbcopy < $SSH_HOSTS_FILE"
  elif has wl-copy; then    echo "wl-copy < $SSH_HOSTS_FILE"
  elif has xclip; then      echo "xclip -selection clipboard < $SSH_HOSTS_FILE"
  else                      echo "cat $SSH_HOSTS_FILE"
  fi
}
SSH_HOSTS_PASTE=""

# Offers to take the server list straight from a Bitwarden note. Only fires when
# there is nothing there yet, so re-running the installer never re-asks.
_ssh_hosts_prompt() {
  SSH_HOSTS_PASTE=""

  # Already have a list: remind how to get it INTO Bitwarden, do not ask again.
  if [ -s "$SSH_HOSTS_FILE" ]; then
    [ "$UI_TTY" = 1 ] && [ "${ASSUME_YES:-0}" != 1 ] && {
      ui_info "back up your server list: $(_ssh_clip_cmd)"
      ui_info "then paste it into the Notes field of your Bitwarden SSH key item"
    }
    return 0
  fi
  if [ "$UI_TTY" != 1 ] || [ "${ASSUME_YES:-0}" = 1 ]; then
    ui_info "no server list yet: run ./install.sh ssh to paste one"
    return 0
  fi

  printf '\n'
  ui_info "No server list yet."
  ui_info ""
  ui_info "On a machine that already has one:"
  ui_info "    $(_ssh_clip_cmd)"
  ui_info "  then paste into the Notes field of your Bitwarden SSH key item."
  ui_info ""
  ui_info "Here: Bitwarden > your SSH key item > copy Notes, then paste below."
  ui_info "Finish with Ctrl-D on an empty line. Ctrl-D straight away skips."
  printf '\n'

  SSH_HOSTS_PASTE="$(cat)"
  printf '\n'
}

_ssh_hosts_write() {
  if [ -z "$SSH_HOSTS_PASTE" ]; then
    [ -s "$SSH_HOSTS_FILE" ] && task_skip "already present" || task_skip "nothing pasted"
    return 0
  fi

  # Anything without a Host line is a mispaste, and a broken file in config.d
  # breaks ssh for every host, not just these.
  if ! printf '%s\n' "$SSH_HOSTS_PASTE" | grep -q '^[[:space:]]*Host[[:space:]]'; then
    task_note "no 'Host' line found, ignored"
    return 1
  fi

  printf '%s\n' "$SSH_HOSTS_PASTE" > "$SSH_HOSTS_FILE"
  chmod 600 "$SSH_HOSTS_FILE"

  # ssh -G parses the whole config. If the paste is malformed, back it out
  # rather than leave every host unusable.
  if ! ssh -G dotfiles-config-check >/dev/null 2>&1; then
    rm -f "$SSH_HOSTS_FILE"
    task_note "config would not parse, discarded"
    return 1
  fi

  task_note "$(grep -c '^[[:space:]]*Host[[:space:]]' "$SSH_HOSTS_FILE") host block(s)"
}

_ssh_perms() {
  local f count=0
  [ -f "$HOME/.ssh/config" ] && chmod 600 "$HOME/.ssh/config"

  for f in "$HOME"/.ssh/*; do
    [ -f "$f" ] || continue
    case "$f" in
      *.pub) chmod 644 "$f"; continue ;;
    esac
    # Match on content, not filename: keys here are named hub-devlab, id_rsa,
    # whatever, and ssh refuses to use a key any group can read.
    if head -n 1 "$f" 2>/dev/null | grep -q 'PRIVATE KEY'; then
      chmod 600 "$f"
      count=$((count + 1))
    fi
  done

  if [ "$count" -gt 0 ]; then
    task_note "$count on-disk key(s) at 600, move them into Bitwarden"
  else
    task_skip "no keys on disk, agent only"
  fi
}
